# Generated by Django 3.0.8 on 2020-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='atracao',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
